image: debian/stable
packages:
  - build-essential
  - cmake
  - ninja-build
  - libsdl2-dev
  - libsdl2-ttf-dev
  - libfreetype-dev
  - bzip2
  - libdrm-dev
  - libgbm-dev
sources:
  - https://git.sr.ht/~henrytill/sdl-bits
tasks:
  - update-submodules: |
      cd sdl-bits
      git submodule update --init --recursive
  - setup: |
      cd sdl-bits
      mkdir build-debug
      cmake -DCMAKE_BUILD_TYPE=Debug -GNinja -B build-debug
  - build: |
      cd sdl-bits
      cmake --build build-debug
  - test: |
      cd sdl-bits
      cmake --build build-debug --target test
